apiVersion: v1
kind: Service
metadata:
  name: lb-svc
  namespace: demo
  labels:
    why: demo
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    why: demo